export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  agendarCita: '/agendar-cita',
  repuestos: '/repuestos',
  admin: '/admin',
  adminClientes: '/admin/clientes',
  adminCitas: '/admin/citas',
  adminOrdenes: '/admin/ordenes',
  adminInventario: '/admin/inventario',
  adminMarcas: '/admin/marcas',
  adminEmpleados: '/admin/empleados',
  adminUsuarios: '/admin/usuarios',
  adminReportes: '/admin/reportes',
  adminAuditoria: '/admin/auditoria',
  adminPerfil: '/admin/perfil',
  adminConfiguracion: '/admin/configuracion',
  // Técnico
  tecnicoDashboard: '/admin/tecnico-dashboard',
  tecnicoOrdenes: '/admin/ordenes-tecnico',
  tecnicoMotos: '/admin/motos-asignadas',
  tecnicoRepuestos: '/admin/solicitud-repuestos',
  tecnicoGanancias: '/admin/ganancias',
}
