export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  agendarCita: '/agendar-cita',
  repuestos: '/repuestos',
  admin: '/admin',
  adminClientes: '/admin/clientes',
  adminCitas: '/admin/citas',
  adminOrdenes: '/admin/ordenes',
  adminInventario: '/admin/inventario',
  adminEmpleados: '/admin/empleados',
  adminUsuarios: '/admin/usuarios',
  adminReportes: '/admin/reportes',
}
